const express = require('express');
const { cadastrar, editarAtividade, desativarAtividade, ativarAtividade, selecionarAtividades, acertar, errar } = require("../controllers/atividadeController");
const router = express.Router();
router.post('/cadastro', cadastrar);
router.put('/editarAtividade', editarAtividade);
router.put('/desativarAtividade', desativarAtividade);
router.put('/ativarAtividade', ativarAtividade);
router.get('/selecionarAtividades', selecionarAtividades);
router.post('/acertar', acertar);
router.post('/errar', errar);
module.exports = router;